### ISSUE TITLE
Update Focal Mode

### ISSUE THREAD

**Issue by pushapsaini** [CST299TeamD/BearWatch#40]

**Comment by peterplatten** [comment]
1) Wind speed should be calm, light, moderate, strong. -Done
2) On bear information page, have upwind/downwind of observer. -Done
3) When bear reacts to something, is the something upwind/downwind of the bear? -Done
4) Ask Tory/Steve/Sarma if there is only Upwind & Downwind? -Waiting for feedback
Keep general direction of wind. (North South etc)
5) Specify "We" in "We can draft a list of food sources to be added." from Steve -Waiting for feedback

**Comment by chriscocker** [comment]
Updates to be revisited with stakeholder feedback during next iteration. Update closed for sprint 1
