### ISSUE TITLE
Research Class opportunities in Application

### ISSUE THREAD

**Issue by peterplatten** [CST299TeamD/BearWatch#6]
Determine how we can use classes to modularize our application.

**Comment by peterplatten** [comment]
Creator's files are nicely modularized already. It's hugely object oriented and defined nicely into modules. With ng-cordova, html divs can have ng-controller tags, which allow a javascript modules to control those divs.

Preet explained it to me, and recommended Chris & I watch this tutorial set (first five to start):
https://www.youtube.com/playlist?list=PL6n9fhu94yhWKHkcL7RJmmXyxkuFB3KSl

I'm going to watch them tonight after school, Chris comment when you have and we'll close this. If I finish before you comment I'll just assign this to you ;)

**Comment by peterplatten** [comment]
Preet and I have watched at least 1-5 of the videos, Chris please close once you have too. They're very valuable.

**Comment by chriscocker** [comment]
Vids 1-5 watched. Great resource
